/**
 * Humanitarian Heritage — canonical design tokens.
 * Source: design/humanitarian-heritage.md
 */

export const HUMANITARIAN_HERITAGE = {
  name: "Humanitarian Heritage",
  colors: {
    surface: "#fff8f7",
    "surface-dim": "#e4d7d7",
    "surface-bright": "#fff8f7",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#fef1f0",
    "surface-container": "#f8ebea",
    "surface-container-high": "#f2e5e5",
    "surface-container-highest": "#ede0df",
    "on-surface": "#201a1a",
    "on-surface-variant": "#544341",
    "inverse-surface": "#362f2f",
    "inverse-on-surface": "#fbeeed",
    outline: "#877270",
    "outline-variant": "#dac1bf",
    "surface-tint": "#954742",
    primary: "#2a0002",
    "on-primary": "#ffffff",
    "primary-container": "#4a0e0e",
    "on-primary-container": "#cc726d",
    "inverse-primary": "#ffb3ad",
    secondary: "#605e5a",
    "on-secondary": "#ffffff",
    "secondary-container": "#e6e2dc",
    "on-secondary-container": "#666460",
    tertiary: "#1a0b02",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#332012",
    "on-tertiary-container": "#a28672",
    error: "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#93000a",
    "primary-fixed": "#ffdad7",
    "primary-fixed-dim": "#ffb3ad",
    "on-primary-fixed": "#3d0506",
    "on-primary-fixed-variant": "#77302d",
    "secondary-fixed": "#e6e2dc",
    "secondary-fixed-dim": "#c9c6c1",
    "on-secondary-fixed": "#1c1c18",
    "on-secondary-fixed-variant": "#484743",
    "tertiary-fixed": "#fedcc5",
    "tertiary-fixed-dim": "#e1c0aa",
    "on-tertiary-fixed": "#29180a",
    "on-tertiary-fixed-variant": "#594231",
    background: "#fff8f7",
    "on-background": "#201a1a",
    "surface-variant": "#ede0df",
  },
  typography: {
    "display-lg": {
      fontFamily: "Montserrat",
      fontSize: "64px",
      fontWeight: "800",
      lineHeight: "1.1",
      letterSpacing: "-0.02em",
    },
    "headline-lg": {
      fontFamily: "Montserrat",
      fontSize: "40px",
      fontWeight: "700",
      lineHeight: "1.2",
      letterSpacing: "-0.01em",
    },
    "headline-md": {
      fontFamily: "Montserrat",
      fontSize: "28px",
      fontWeight: "700",
      lineHeight: "1.3",
    },
    "body-lg": {
      fontFamily: "Montserrat",
      fontSize: "18px",
      fontWeight: "400",
      lineHeight: "1.6",
      letterSpacing: "0.01em",
    },
    "body-md": {
      fontFamily: "Montserrat",
      fontSize: "16px",
      fontWeight: "400",
      lineHeight: "1.6",
    },
    "label-lg": {
      fontFamily: "Montserrat",
      fontSize: "14px",
      fontWeight: "600",
      lineHeight: "1.2",
      letterSpacing: "0.08em",
    },
    "display-lg-mobile": {
      fontFamily: "Montserrat",
      fontSize: "36px",
      fontWeight: "800",
      lineHeight: "1.1",
    },
  },
  rounded: {
    sm: "0.25rem",
    DEFAULT: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    full: "9999px",
  },
  spacing: {
    unit: "8px",
    "container-max": "1280px",
    gutter: "24px",
    "margin-mobile": "16px",
    "margin-desktop": "64px",
    "section-gap": "120px",
  },
} as const;

/** CSS custom property map for :root light mode */
export const HUMANITARIAN_HERITAGE_CSS_VARS: Record<string, string> = {
  "--background": HUMANITARIAN_HERITAGE.colors.background,
  "--foreground": HUMANITARIAN_HERITAGE.colors["on-background"],
  "--surface": HUMANITARIAN_HERITAGE.colors.surface,
  "--surface-dim": HUMANITARIAN_HERITAGE.colors["surface-dim"],
  "--surface-bright": HUMANITARIAN_HERITAGE.colors["surface-bright"],
  "--surface-container-lowest": HUMANITARIAN_HERITAGE.colors["surface-container-lowest"],
  "--surface-container-low": HUMANITARIAN_HERITAGE.colors["surface-container-low"],
  "--surface-container": HUMANITARIAN_HERITAGE.colors["surface-container"],
  "--surface-container-high": HUMANITARIAN_HERITAGE.colors["surface-container-high"],
  "--surface-container-highest": HUMANITARIAN_HERITAGE.colors["surface-container-highest"],
  "--surface-variant": HUMANITARIAN_HERITAGE.colors["surface-variant"],
  "--surface-tint": HUMANITARIAN_HERITAGE.colors["surface-tint"],
  "--on-surface": HUMANITARIAN_HERITAGE.colors["on-surface"],
  "--on-surface-variant": HUMANITARIAN_HERITAGE.colors["on-surface-variant"],
  "--on-background": HUMANITARIAN_HERITAGE.colors["on-background"],
  "--outline": HUMANITARIAN_HERITAGE.colors.outline,
  "--outline-variant": HUMANITARIAN_HERITAGE.colors["outline-variant"],
  "--primary": HUMANITARIAN_HERITAGE.colors.primary,
  "--on-primary": HUMANITARIAN_HERITAGE.colors["on-primary"],
  "--primary-container": HUMANITARIAN_HERITAGE.colors["primary-container"],
  "--on-primary-container": HUMANITARIAN_HERITAGE.colors["on-primary-container"],
  "--primary-fixed": HUMANITARIAN_HERITAGE.colors["primary-fixed"],
  "--primary-fixed-dim": HUMANITARIAN_HERITAGE.colors["primary-fixed-dim"],
  "--on-primary-fixed": HUMANITARIAN_HERITAGE.colors["on-primary-fixed"],
  "--on-primary-fixed-variant": HUMANITARIAN_HERITAGE.colors["on-primary-fixed-variant"],
  "--secondary": HUMANITARIAN_HERITAGE.colors.secondary,
  "--on-secondary": HUMANITARIAN_HERITAGE.colors["on-secondary"],
  "--secondary-container": HUMANITARIAN_HERITAGE.colors["secondary-container"],
  "--on-secondary-container": HUMANITARIAN_HERITAGE.colors["on-secondary-container"],
  "--secondary-fixed": HUMANITARIAN_HERITAGE.colors["secondary-fixed"],
  "--secondary-fixed-dim": HUMANITARIAN_HERITAGE.colors["secondary-fixed-dim"],
  "--on-secondary-fixed": HUMANITARIAN_HERITAGE.colors["on-secondary-fixed"],
  "--on-secondary-fixed-variant": HUMANITARIAN_HERITAGE.colors["on-secondary-fixed-variant"],
  "--tertiary": HUMANITARIAN_HERITAGE.colors.tertiary,
  "--on-tertiary": HUMANITARIAN_HERITAGE.colors["on-tertiary"],
  "--tertiary-container": HUMANITARIAN_HERITAGE.colors["tertiary-container"],
  "--on-tertiary-container": HUMANITARIAN_HERITAGE.colors["on-tertiary-container"],
  "--tertiary-fixed": HUMANITARIAN_HERITAGE.colors["tertiary-fixed"],
  "--tertiary-fixed-dim": HUMANITARIAN_HERITAGE.colors["tertiary-fixed-dim"],
  "--on-tertiary-fixed": HUMANITARIAN_HERITAGE.colors["on-tertiary-fixed"],
  "--on-tertiary-fixed-variant": HUMANITARIAN_HERITAGE.colors["on-tertiary-fixed-variant"],
  "--error": HUMANITARIAN_HERITAGE.colors.error,
  "--on-error": HUMANITARIAN_HERITAGE.colors["on-error"],
  "--error-container": HUMANITARIAN_HERITAGE.colors["error-container"],
  "--on-error-container": HUMANITARIAN_HERITAGE.colors["on-error-container"],
  "--inverse-surface": HUMANITARIAN_HERITAGE.colors["inverse-surface"],
  "--inverse-on-surface": HUMANITARIAN_HERITAGE.colors["inverse-on-surface"],
  "--inverse-primary": HUMANITARIAN_HERITAGE.colors["inverse-primary"],
};